### ISSUE TITLE
Triangle counting simple graph doesn't work

### ISSUE THREAD

**Issue by yunduz** [masabahmad/CRONO#2]
Hello,

For triangle counting I've tried to provide a file with a simple, 3 nodes graph which makes one triangle like this:
0    1
1    2
2    0

However, the output says:
 .gr graph with parameters: Vertices:1 Degree:1 

File Read, Largest Vertex:1
Threads Joined!
Time Taken:
0.000009 seconds
Triangles=0 

This seems to be incorrect. Could you let me know if my file format is wrong or it's something else?

Thanks,

Yunduz

**Comment by masabahmad** [comment]
Hi Yunduz,

The Input .gr file should have the first 4 lines commented, starting with #. Then you start the vertex edge combinations.

I also updated the code with floating precision, which fixes the 0 count problem stemming from int  values truncating edge additions. Running your graph gives the count as 1.

Regards
Masab

**Comment by yunduz** [comment]
Hi Masab,

Thank you very much for such a quick response!

I tried the following graph (two triangles):
#
#
#
#
0	1
1	2
2	0
2	3
3	1

And the output is 1 triangle. I tried debugging it but I am not sure what's exactly wrong. I think one of the possible issues is that in: https://github.com/masabahmad/CRONO/blob/master/apps/triangle_counting/triangle_counting_lock.cc#L96
largest should be largest_d
I am also not clear why do you divide by 3 when calculating total number of triangles.
One more thing I noticed, if the last line in a file is blank, W array ends up being incorrect.

I appreciate your help :)

**Comment by masabahmad** [comment]
There may be some assumptions required by the algorithm that I am not
entirely aware of. I can look into another algorithm for you and post it
with the code in a day or two.

As for the last blank line issue. That will happen because the graph file
reader ends at the eof def. One can put an exception handler that does not
read blank lines.

Regards
Masab

**Comment by yunduz** [comment]
Maybe I just don't understand the algorithm, but it seems it's not the same as in [12]. I could be completely wrong though!!!

**Comment by masabahmad** [comment]
Hi,

I have added an older version of the algorithm that works with your graphs. This version requires sorted neighbors, hence I didnt add it earlier. It seems to work as you require. Just comment out lines 96 and 97 for it to work with your file. The condition is there to prune out work (hence the heuristic).

[12] themselves have used an algorithm used in another paper. The citations twerk back to some theoretical paper.

Let me know if you have other questions.

Regards
Masab

**Comment by yunduz** [comment]
Thanks, Masab, I will check it out!

**Comment by yunduz** [comment]
I am still curious about the original algorithm, would like to understand it. It seems like after this for loop completes (https://github.com/masabahmad/CRONO/blob/master/apps/triangle_counting/triangle_counting_lock.cc#L89), you have D filled in. After this, all that threads are doing are summing up entries of it, so technically you can replace 114 - 150 with a loop that sums up entries of D and then at the end divides the sum by 3 (just like in line 149). What am I missing here? and why would this give number of triangles?

P.S.: very sorry to bug you so much, but I just have to know :)

**Comment by masabahmad** [comment]
[12] reads in its triangle counting explanation: "With undirected edges, the total number of overlaps gives 3 times the number of triangles." This is where the divide by three comes from. I guess its a heuristic to reduce complexity. In the sorted_neighbors code you can see that there is an additional for loop and also an additional while loop (this increases the complexity over O(V+E)). The algorithm approximates these inner loops by adding the number of connections, and then just dividing by three at the end. 

What you are saying about the parallelization is also correct. With time the heuristic in my code has become simpler, so you dont need an additional barrier and thus you can sum up the work in the prior phase. Earlier the code in this middle redundant phase was a bit more complex, as it required data from other threads, and hence a lock. This could only be done after a barrier when the D array values are set in the prior phase.

You can bug me as much as you want lol. Might I ask for what purpose are you using these benchmarks?

**Comment by yunduz** [comment]
Oh I see, it's an approximation! Makes sense now! Thanks!

I am looking for benchmarks for my thesis project (doing Master's in CS). Your triangle counting benchmark looks promising since threads increment shared variables (values in D) and that's one of the cases I am looking for.

**Comment by masabahmad** [comment]
Ok cool.

You can also look at sssp. It also updates distances in an array via locks.
You can further generate a dense synthetic graph to increase contention on
shared data.

Masab

**Comment by yunduz** [comment]
Thanks for the tip!
