### ISSUE TITLE
Community detection

### ISSUE THREAD

**Issue by yunduz** [masabahmad/CRONO#3]
Hi Masab,

I have a couple of questions :)
1. Here https://github.com/masabahmad/CRONO/blob/master/apps/community/community_lock.cc#L165  W_f[v][i] is protected with a mutex, could you explain why it is needed since it seems that each thread has their own partition over vertices and they don't overlap?
2. Here https://github.com/masabahmad/CRONO/blob/master/apps/community/community_lock.cc#L182 each comm[i] in all of the threads would be set to the same value since the right hand side contains only constants. Is there smth missing or smth I don't understand?

Thanks,

Yunduz

**Comment by masabahmad** [comment]
Hi Yunduz,

1. W_f[v][i] is the i'th neighbor of a vertex v. The vertices are
partitioned among threads. However, W_f[v][i] could have shared neighbors.
If thread 0 has vertex 99 (W_f[99]), and thread 1 has vertex 100
(W_f[100]), but they have a common neighbor that is vertex 200 in another
thread (W_f[99][0], W_f[100][1]), then this requires some sort of atomic
update as both threads will attempt to write to it.

2. It is an approximate reduction heuristic, and you are right, it puts a
constant value depending on the total number of threads, P. The notion is
that as you add more threads, the more the comm array deviates from its
comparable comm array when run at 1 thread. So this somehow attempts to fix
that by setting constants into the comm array, that allows for a smaller
deviation from the original comm array. One can use other heuristics if
possible as well.

Regards
Masab

**Comment by yunduz** [comment]
1.I think I still don't understand. Say yes, the two threads have a common neighbour but two threads are writing to two different locations since W_f is an array of array of floats, so they would't race to write to the same location.
2. I thought at the end of do_work, comm would contain community for each vertex. If it's not the case, where are the final community assignments stored?

Once again, thank you so much for explanations :)

**Comment by masabahmad** [comment]
1. It is the same address. W_f[99][0], W_f[100][1] point to the same
address that directs to vertex 200.

2. comm does have the final communities. Its just the way the communities
are assigned, which goes through multiple phases, one of which has a
heuristic.

**Comment by yunduz** [comment]
But W_f[99][0], W_f[100][1] are not addresses, these are floats, W_f is declared as float**.

**Comment by yunduz** [comment]
No worries! This is a rare case that I am right haha

Thanks for all the help, you're the fastest replyer I've encountered!

**Comment by masabahmad** [comment]
No problem. I'll update the code in a bit.

Thanks
Masab
