### ISSUE TITLE
Betweennes Centrality: atomic locks version?

### ISSUE THREAD

**Issue by yunduz** [masabahmad/CRONO#4]
Hi Masab,

In your paper it says: "The final loop is statically divided amongst threads, with each thread reading  shortest path values and updating the centralities via atomic locks." I noticed that in the implementation there is no part where threads use atomic locks. I am wondering if you had an earlier version that did and if you could post it?

Thanks,

Yunduz

**Comment by masabahmad** [comment]
Hi Yunduz,

Yes the earlier version has sigma[neighbor] instead of
sigma[tid][neighbor], hence multiple threads incrementing sigma[neighbor]
would require locks.

I'll have to look for the code. I'll post it in the next few days if i find
it.

Regards
Masab

**Comment by yunduz** [comment]
Thanks Masab!

**Comment by masabahmad** [comment]
Hi Yunduz,

I have added the version of bc that uses locks. You can have a look at it and let me know if there are any issues.

Regards
Masab
