### ISSUE TITLE
Sigma 2D matrix memory allocation in 'bc' benchmark

### ISSUE THREAD

**Issue by ShehabElsayed** [masabahmad/CRONO#7]
I was running some tests with 'bc' benchmark but kept running into "Corrupted double-linked list" errors. Upon further investigation I noticed this part in the code responsible for memory allocation for sigma matrix in main.

```cpp
//Memory allocations for the input graph
int** W = (int**) malloc(N*sizeof(int*));
int** W_index = (int**) malloc(N*sizeof(int*));
int** sigma = (int**) malloc(P*sizeof(int*));
for(int i = 0; i < N; i++)
{
     //W[i] = (int *)malloc(sizeof(int)*N);
     delta[i]=0;
     avg[i]=0;
     int ret = posix_memalign((void**) &W[i], 64, DEG*sizeof(int));
     int re1 = posix_memalign((void**) &W_index[i], 64, DEG*sizeof(int));
     int re2 = posix_memalign((void**) &sigma[i], 64, N*sizeof(int));
     if (ret != 0 || re1!=0 || re2!=0)
     {
         fprintf(stderr, "Could not allocate memory\n");
         exit(EXIT_FAILURE);
     }
}
```

If I understand correctly, sigma is supposed to be a 2D matrix (PxN) where P in the number of threads and N is the number of vertices. However, the for loop goes for N iterations and in each iteration allocates memory for a row in sigma. But sigma has P rows and not N!!!.

I separated the sigma memory allocation in another loop and the problem I was having seems to have gone away. Here are my modified memory allocation loops.

```cpp
for(int i = 0; i < N; i++)
{
     //W[i] = (int *)malloc(sizeof(int)*N);
     delta[i]=0;
     avg[i]=0;
     int ret = posix_memalign((void**) &W[i], 64, DEG*sizeof(int));
     int re1 = posix_memalign((void**) &W_index[i], 64, DEG*sizeof(int));
     //int re2 = posix_memalign((void**) &sigma[i], 64, N*sizeof(int));
     //if (ret != 0 || re1!=0 || re2!=0)
     if (ret != 0 || re1!=0)
     {
         fprintf(stderr, "Could not allocate memory\n");
         exit(EXIT_FAILURE);
     }
}

// The new sigma memory allocation loop
for(int i = 0; i < P; i++)
{
    int re2 = posix_memalign((void**) &sigma[i], 64, N*sizeof(int));
    if (re2!=0)
    {
        fprintf(stderr, "Could not allocate memory\n");
        exit(EXIT_FAILURE);
    }
}
```

Is my understanding and fix correct or did I misinterpret something in the code?

**Comment by masabahmad** [comment]
Yes what you did is correct. Let me know if you want to push these changes to the repository.

Thanks
Masab

**Comment by ShehabElsayed** [comment]
Thank you very much for your reply. I will be happy to push these changes to the repo.

**Comment by ShehabElsayed** [comment]
Should I go ahead and create a Pull Request?

**Comment by masabahmad** [comment]
Yes you can.
